export const WEATHER_BASE_URL = 'https://api.weatherstack.com';
export const ACTION_TYPES = {
  SEARCH_RESULT: 'SEARCH_RESULT',
  SET_WEATHER_CURRENT: 'SET_WEATHER_CURRENT',
  SET_WEATHER_FORECAST: 'SET_WEATHER_FORECAST',
  ADD_CITIES: 'ADD_CITIES',
  REMOVE_CITY: 'REMOVE_CITY',
  TOGGLE_FAVORITES: 'TOGGLE_FAVORITES'
};
